src/Entity/Auteur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;


/**
 * //j'utilise l'annotation @ORM\Entity pour declarer ma classe en tant qu'entité == table
 * @ORM\Entity(repositoryClass="App\Repository\AuteurRepository")
 */
class Auteur
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="date")
     */
    private $birthDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $deathDate;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $biography;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getDeathDate(): ?\DateTimeInterface
    {
        return $this->deathDate;
    }

    public function setDeathDate(?\DateTimeInterface $deathDate): self
    {
        $this->deathDate = $deathDate;

        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;

        return $this;
    }
}

src/Entity/Book.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookRepository")
 */
class Book
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_pages;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $style;


    /**
     * @ORM\Column(type="boolean")
     */
    private $ins_stock;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getNbPages(): ?int
    {
        return $this->nb_pages;
    }

    public function setNbPages(int $nb_pages): self
    {
        $this->nb_pages = $nb_pages;

        return $this;
    }

    public function getStyle(): ?string
    {
        return $this->style;
    }

    public function setStyle(string $style): self
    {
        $this->style = $style;

        return $this;
    }

    public function getInsStock(): ?bool
    {
        return $this->ins_stock;
    }

    public function setInsStock(bool $ins_stock): self
    {
        $this->ins_stock = $ins_stock;

        return $this;
    }
}

src/Controller/AuteurController.php
<?php

namespace App\Controller;

use App\Repository\AuteurRepository;
use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class AuteurController extends AbstractController
{
    /**
     * @Route("/auteur", name="auteur")
     */
    public function index()
    {
        return $this->render('auteur/index.html.twig', [
            'controller_name' => 'AuteurController',
        ]);
    }
    /**
     * @Route("/auteur_list", name="auteur_list")
     */
    public function auteurList(AuteurRepository $auteurRepository)
    {
        $auteurList = $auteurRepository->findAll();
        return $this->render('auteur/auteur.html.twig', [
            'auteurList' => $auteurList
        ]);
    }

        /**
     * @Route("/auteur{id}", name="auteur_id")
     */
    public function auteur(AuteurRepository $auteurRepository, $id){
        $auteur = $auteurRepository->find($id);
        return $this->render('auteur/auteurId.html.twig',[
            'auteur' => $auteur
        ]);


    }

    /**
     * @Route("/auteur_Bio/{word}", name="auteur_Bio")
     */
    public function getauteurbyBio(AuteurRepository $auteurRepository, $word)
    {//auteur repository contient une instance de la classe 'auteurRepository
        //généralement on obtient une instance de la classe objet en utilisant le mot clé 'new'
        $auteurs = $auteurRepository->GetAuteurByBio($word);
        //J'appelle la methode getauteurbybio de mon repo auteur
        // et je passe en parametre la variable word'
       // cette methode ira chercher les mots dans biographie
        return $this->render('auteur/auteur.html.twig',[
            'auteur' => $auteurs
        ]);

    }
}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Repository\BookRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class BooksController extends AbstractController
{
    /**
     * @Route("/books", name="books")
     */
    public function index()
    {
        return $this->render('books/index.html.twig', [
            'controller_name' => 'BooksController',
        ]);
    }

    /**
     * @Route("/books_list", name="books_list")
     */
    public function booksList(BookRepository $bookRepository)
    {
        // je cherche mes fichiers dans le repository (et j'utilise la methode find all)
        // pour pouvoir selectionner tous les elements de ma table book
        //les repository servent a faire les requetes select dans les tables
        $booksList = $bookRepository->findAll();
        return $this->render('books/booksList.html.twig', [
            'booksList' => $booksList
        ]);
    }
        /**
         * @Route("/book/{id}", name="book")
         */
        private $auteur;
        public function book(BookRepository $bookRepository , $id){

            $book = $bookRepository->find('$id');
            return $this->render('books/book.html.twig',[
                'book' => $book
            ]);
    }
        /**
        * @Route("/book_by_style", name="book_by_style")
        */
        public function getBooksByStyle(BookRepository $bookRepository)
        {
            $books = $bookRepository->GetByGenre();

            dump($books); die;
            //verification de la page      var dump('hello Books');die;
            // appelle le bookrepository
            //on appelle la méthode getByGenre qui nous retourne tous les livres en fonction d'un genre'
        }




}

templates/auteur/auteur.html.twig
    <!doctype html>
    <html lang="fr">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport"
                  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
            <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <title>ma liste auteur</title>
            <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    <body>
    <h1 id="title">Voici la liste de mes auteurs</h1>
    {% for auteur in auteurList %}
        <a class="grille">
            <div id="bloc">
                <a href="{{ path ('auteur_id', {'id': auteur.id}) }}">

                <strong>{{ auteur.name }} {{ auteur.firstName }}</strong></a>

            </div>

            <div id="bloc">
                {{ auteur.birthDate|date("d/ m/ Y") }}
            </div>
            <div id="bloc">
                {{ auteur.deathDate|date("d/ m/ Y") }}
            </div>
                <div id="bloc">
                    {{ auteur.biography }}

        </div>
    </div>
    {% endfor %}

    </body>
</html>

templates/auteur/auteurId.html.twig
{% extends 'base2.html.twig' %}

{% block title %}

{% endblock %}

{% block categorie %}
    des auteurs
{% endblock  %}



{% block content %}
    <article class="preview">

        <h2>{{ auteur.firstName }} {{ auteur.name }}</h2>
        <p>né le {{ auteur.birthDate|date("d/m/Y")}}
            {% if auteur.deathDate is not null %}
                et mort le {{ auteur.deathDate|date("d/m/Y") }}{% endif %}</p>
        <p>Biographie {{ auteur.biography}}</p>
    </article>
{% endblock %}

templates/auteur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuteurController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code
    { display:grid;grid-column: 200px 400px 200px;background: #265224; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Bonjour Samuel {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>auteurs <code><a href="{{ path ('auteur/auteur.html.twig') }}"></a></code></li>

        <li>Biographie <code><a href="{{ path ('auteur/auteur.html.twig')}}"></a></code></li>
    </ul>
</div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Salut!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}



        {% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/base2.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/style_baptiste.css">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<header>
    <nav>
        <ul>
            <li><h1 class="titre">Bienvenue sur ton auteur préféré</h1></li>
            <li><a href="{{ path('books_list') }}">Nos livres</a></li>
            <li><a href="{{ path('auteur_list') }}">Nos auteurs</a></li>
        </ul>
    </nav>

</header>

<main>
    <h1 class="presentation">Retrouvez la liste {% block categorie %}{% endblock %}</h1>
    <div class="contenu">
        {% block content %}
        {% endblock  %}
    </div>
</main>




<footer>

</footer>
</body>
</html>

templates/books/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nos livres
{% endblock %}


{% block categorie %}
    <a href="{{ path ('book', {id : book.id}) }}"
{% endblock  %}



{% block content %}

        <ul>
    {% for book in books-list %}
            <li>
                "{{ book.titre }}"
                par {{ book.auteur.lastname}}
                {{ book.auteur.name}}
            </li>
    {% endfor %}
        </ul>

{% endblock %

templates/books/booksList.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{{ asset('css/style2.css') }}">
<body>
<h1 id="title">Voici la liste de mes books</h1>

{% for books in booksList %}
<article>
    <div id="title">
        {{ books.title }}
    </div>
    <div id="title">Nb.
        {{ books.nbPages }}
    </div>
    <div id="title">Genre
        {{ books.style }}
    </div>
    <div id="title">
        {{ books.insStock }}
    </div>

</article>



{% endfor %}

</body>
</html>

templates/books/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BooksController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/Applications/MAMP/htdocs/my_third_project_sf/src/Controller/BooksController.php'|file_link(0) }}">src/Controller/BooksController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/Applications/MAMP/htdocs/my_third_project_sf/templates/books/index.html.twig'|file_link(0) }}">templates/books/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}